test push

diff --git a/.github/workflows/push-server-image.yml b/.github/workflows/push-server-image.yml
--- a/.github/workflows/push-server-image.yml
+++ b/.github/workflows/push-server-image.yml
@@ -1,9 +1,9 @@
 name: GitHub Actions Demo
 run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
-on: 
- push: 
-  paths: 
-    - 'server/**'
+on:
+  push:
+    paths:
+      - "server/**"
 jobs:
   Explore-GitHub-Actions:
     runs-on: ubuntu-latest
@@ -16,7 +16,7 @@ jobs:
 
       - name: Check out repository code
         uses: actions/checkout@v4
-        
+
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
@@ -33,11 +33,11 @@ jobs:
       - name: Verify JAR file exists
         working-directory: server
         run: |
-         ls build/libs
-         if [ ! -f build/libs/*.jar ]; then
-           echo "JAR file not found!"
-           exit 1
-         fi
+          ls build/libs
+          if [ ! -f build/libs/*.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -57,3 +57,4 @@ jobs:
         # run: |
         # ls ${{ github.workspace }}
       # - run: echo "🍏 This job's status is ${{ job.status }}."
+      # pushtest
